### ISSUE TITLE
Roll Die enhancements

### ISSUE THREAD

**Issue by jenniferplusplus** [careecodes/Cracking-The-Interview-Sample-Solutions#1]
😜❤

1. Needs a readme
2. Some games use custom symbolic dice, rather than dice with numbers. How could the die rolling solution be expanded to accommodate that use case?

**Comment by careecodes** [comment]
Oooooooh! 

My first thought is to use an array and read through it similar to my first solution. But I wonder if there's a better way than this? Also a way to pass in the symbols so that it's dynamic?

**Comment by jenniferplusplus** [comment]
Yeah, that's what I would do. I did a similar thing on the clapback generator.

https://github.com/jenniferplusplus/clapbackplusplus/blob/master/src/lib/rand-array.js
